name: Deploy Angular App to S3

on:
  workflow_dispatch:
  push:
    branches:
      - main  # Déclenche le workflow sur les pushes vers la branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Amplify webhook
      run: curl -X POST -d {} "https://webhooks.amplify.eu-west-3.amazonaws.com/prod/webhooks?id=10b02dbf-401e-42b0-949e-fefcbf20be77&token=${{ secrets.AMPLIFY_TOKEN }}&operation=startbuild" -H "Content-Type:application/json"
